name: Remote Dispatch Action Initiator

on:
  push:
  schedule:
    - cron: '0 12 * * *'
  repository_dispatch:

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: PING - Dispatch initiating repository event
        if: github.event.action != 'pr1'
        run: |
          curl -X POST https://api.github.com/repos/flooie/pingme/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "pr1", "client_payload": { "repository": "flooie/pingme" }}'
      - name: ACK - Acknowledge pong from remote repository
        if: github.event.action == 'pong'
        run: |
          echo "PONG received from '${{ github.event.client_payload.repository }}'" 
