name: Reporters-DB PR

on:
  pull_request: # turn this to pull request and then identify the PR number send that and then run the code against it and pass it back.

jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TOKEN }}
          repository: flooie/pingme
          event-type: reporters-db-pr
          client-payload: '{"ref": "${{ github.ref }}", "pr_number": "${{ github.event.number }}", "commit": "d341cf38693d3e79aa856bd37cd0843c58b66e05", "gsha": "${{ github.event.pull_request.head.sha }}" }'